### ISSUE TITLE
Translations does not stick when navigating

### ISSUE THREAD

**Issue by YotQues** [nadavWeisler/PsychInfo#107]
When switching to English and navigating to a different page, sometimes it flashes in Hebrew before displaying the relevant language, and when navigating to "מידע פסיכולוגי" the language is reset to Hebrew.

**Comment by ShlomiShitrit** [comment]
@nadavWeisler  @YotQues  for me the navigation works fine. When you go back to the home page, it does go back to hebrew because it's the default lang. I think it's fine, and I saw a lot of websites working like this.

**Comment by ShlomiShitrit** [comment]
after talking to @nadavWeisler , we foun a solution: rendering the page from the [lng]/components
