### ISSUE TITLE
באג בתצוגה בטלפון של הנושאים לדוגמה בעמוד הבית

### ISSUE THREAD

**Issue by GayaAran** [nadavWeisler/PsychInfo#130]
תכנים שהם יותר משורה **בטלפון** מתלבשים על התכנים הבאים - הבלוקים שלהם לא ממשיכים איתם (להבהרה אפשר לראות את התמונה). זה קורה כשנכנסים לפלטורים המוצעים בעמוד הבית (בעמוד של תוכן לתעסוקה והסחת דעת נניח), לאו דווקא כשעושים סינון אישי עם התגיות.

![WhatsApp Image 2023-10-24 at 14 39 29_49cc2156](https://github.com/nadavWeisler/PsychInfo/assets/69464818/a2e67bfd-0c22-46c5-84a5-c21d783ac58a)

**Comment by nadavWeisler** [comment]
קורה גם במחשב: 

![image](https://github.com/nadavWeisler/PsychInfo/assets/32937058/6be2f68d-2478-46e3-855c-c0141f2680cc)
