### ISSUE TITLE
אפיון ושינוי פסקת עמוד בית

### ISSUE THREAD

**Issue by nadavWeisler** [nadavWeisler/PsychInfo#132]
1. הורדת רמה
2. לקצר, להוריד אודות (לפחות בעומק)
3. וולקאם שמח

**Comment by ShlomiShitrit** [comment]
@GayaAran  How is it going?

**Comment by GayaAran** [comment]
@ShlomiShitrit 
לשנות לטקסט הזה (עם יישור לשני הצדדים ושמירה על המרווחים):

****

זה בסדר להרגיש לא יציב.
זה בסדר להזדקק לעזרה.
זה בסדר לא להיות בסדר.

אם הרגשתם מוצפים בתקופה הזו, גם כשניסיתם לחפש מידע בנוגע לתמיכה נפשית, אתם כמובן לא היחידים. 

אנחנו מזמינים אתכם ואתכן להשתמש באתר הזה כדי למצוא מידע מרוכז ומהימן הנוגע להתמודדות נפשית בעקבות אירועי ה-7 באוקטובר, להיעזר בנושאים הנבחרים המוצעים בתחתית העמוד, או ללחוץ על כפתור ה"**התחלה**" כדי למצוא את התוכן שאתם זקוקים לו באופן שמותאם במיוחד אליכם.

איתכם תמיד,
צוות PsychInfo
