### ISSUE TITLE
התאמה לנגישות

### ISSUE THREAD

**Issue by nadavWeisler** [nadavWeisler/PsychInfo#137]

**Comment by An-Ko** [comment]
טקסט כללי בעמוד הראשי:
![image](https://github.com/nadavWeisler/PsychInfo/assets/50925068/cd0ff2d5-6024-484f-bcdb-222bee8da594)
בגלל הבהירות (בהיקות?) השונה בין שני צבעי הרקע, השילוב בינהם גורם לטקסט על הצבע הבהיר פחות (כחול) להיות פחות קריא.
לדעתי כדאי להחליף את הצבע לצבע עם בהירות דומה ו\או לאפשר הפיכה של הרקע לצבע אחיד למי שמתקשה לקרוא.

היררכיה של כותרות:
כרגע הכל בנוי בעיקר מאלמנטי div, ראיתי גם שימוש ב-h4 אבל לא את הקודמים לו.

אלמנט label בטפסים:
עבור קוראי מסך, כדאי שיופיע ליד כל שדה בו צריך להזין מידע - למיטב ידיעת legend לא מחליף label.

הגדרת lang עבור אלמנט ה-html, לפי השפה של העמוד
