### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by An-Ko** [nadavWeisler/PsychInfo#156]
Some text is not translated.

**General**
 - Page title (html)

**Main Page**
- Topics
- Therapist call to action button (Arabic, Russian - appears in English instead)
- 2nd list item in description (Russian - appears in Hebrew)

**About Us**
 - Description
 - Team members contribution / titles (Some aren't translated at all, some are only translated to English + one other language for the translators)
 - Title (Arabic - appears in Hebrew, Russian - appears in English)

**Register Therapists**
 - Description
 - Form legends (Arabic, Russian)

**Found a Mistake**
 - Everything (Arabic, Russian - appears in Hebrew instead)

**Admin Login** (don't know if it's relevant)
 - Everything (Arabic, Russian - appears in Hebrew instead)

**Comment by ShlomiShitrit** [comment]
@ShirBerebbi  Is there any update on this?
