### ISSUE TITLE
להרחיב קצת את המקום של הכותרות שיתפוס יותר מקום ואז יהיה אולי יותר מרווח

### ISSUE THREAD

**Issue by nadavWeisler** [nadavWeisler/PsychInfo#76]
![image](https://github.com/nadavWeisler/PsychInfo/assets/32937058/31d61e6f-d021-4214-af33-75c7b2aa308d)

**Comment by ShlomiShitrit** [comment]
לא כל כך הבנתי. זה עדיין רלוונטי עם העיצוב החדש?  @nadavWeisler

**Comment by nadavWeisler** [comment]
לא נראה לי, סוגר
